# version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=KemminaThakadu04!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
  #  volumes:
  #    - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - sql-network

#volumes:
#  sqlserver_data:
#    driver: local

networks:
  sql-network:
    driver: bridge